{
 "title": "Application Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component Status",
   "type": "stat",
   "description": "This panel shows the connection status of all application components in the system. Currently, the Producer and Consumer are not yet implemented.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"kafka|zookeeper|mongodb\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[1m])",
     "legendFormat": "{{instance}} - CPU"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Producer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Message Rate",
     "type": "graph",
     "description": "This panel will show producer message rate when implemented.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(producer_messages_sent_total[1m])",
       "legendFormat": "Messages Sent"
      }
     ]
    },
    {
     "title": "Producer Error Rate",
     "type": "graph",
     "description": "This panel will show producer error rate when implemented.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(producer_message_send_failures_total[1m])",
       "legendFormat": "Error Rate {{error_type}}"
      }
     ]
    },
    {
     "title": "Producer Message Latency",
     "type": "graph",
     "description": "Shows the latency of message send operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(producer_message_send_latency_seconds_sum[1m]) / rate(producer_message_send_latency_seconds_count[1m])",
       "legendFormat": "Send Latency"
      }
     ]
    },
    {
     "title": "Producer Batch Size",
     "type": "graph",
     "description": "Shows the batch size distribution",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(producer_batch_size_sum[1m]) / rate(producer_batch_size_count[1m])",
       "legendFormat": "Avg Batch Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer-1 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer-1 Processing Rate",
     "type": "graph",
     "description": "This panel shows consumer-1 message processing rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_messages_processed_total{instance=~\"consumer-1:.*\"}[1m])",
       "legendFormat": "Messages Processed"
      }
     ]
    },
    {
     "title": "Consumer-1 Error Rate",
     "type": "graph",
     "description": "This panel shows consumer-1 error rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_processing_errors_total{instance=~\"consumer-1:.*\"}[1m])",
       "legendFormat": "Error Rate"
      }
     ]
    },
    {
     "title": "Consumer-1 Lag",
     "type": "graph",
     "description": "Shows the consumer-1 lag (number of messages behind the latest offset)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_lag{instance=~\"consumer-1:.*\"}",
       "legendFormat": "Consumer Lag"
      }
     ]
    },
    {
     "title": "Consumer-1 Processing Times",
     "type": "graph",
     "description": "Shows the time spent processing messages and writing to MongoDB for consumer-1",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_processing_time_seconds_sum{instance=~\"consumer-1:.*\"}[1m]) / rate(consumer_processing_time_seconds_count{instance=~\"consumer-1:.*\"}[1m])",
       "legendFormat": "Processing Time"
      },
      {
       "expr": "rate(consumer_mongodb_write_time_seconds_sum{instance=~\"consumer-1:.*\"}[1m]) / rate(consumer_mongodb_write_time_seconds_count{instance=~\"consumer-1:.*\"}[1m])",
       "legendFormat": "MongoDB Write Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer-2 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer-2 Processing Rate",
     "type": "graph",
     "description": "This panel shows consumer-2 message processing rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_messages_processed_total{instance=~\"consumer-2:.*\"}[1m])",
       "legendFormat": "Messages Processed"
      }
     ]
    },
    {
     "title": "Consumer-2 Error Rate",
     "type": "graph",
     "description": "This panel shows consumer-2 error rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_processing_errors_total{instance=~\"consumer-2:.*\"}[1m])",
       "legendFormat": "Error Rate"
      }
     ]
    },
    {
     "title": "Consumer-2 Lag",
     "type": "graph",
     "description": "Shows the consumer-2 lag (number of messages behind the latest offset)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_lag{instance=~\"consumer-2:.*\"}",
       "legendFormat": "Consumer Lag"
      }
     ]
    },
    {
     "title": "Consumer-2 Processing Times",
     "type": "graph",
     "description": "Shows the time spent processing messages and writing to MongoDB for consumer-2",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(consumer_processing_time_seconds_sum{instance=~\"consumer-2:.*\"}[1m]) / rate(consumer_processing_time_seconds_count{instance=~\"consumer-2:.*\"}[1m])",
       "legendFormat": "Processing Time"
      },
      {
       "expr": "rate(consumer_mongodb_write_time_seconds_sum{instance=~\"consumer-2:.*\"}[1m]) / rate(consumer_mongodb_write_time_seconds_count{instance=~\"consumer-2:.*\"}[1m])",
       "legendFormat": "MongoDB Write Time"
      }
     ]
    }
   ]
  }
 ]
}