{
 "title": "Persistence Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "MongoDB Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mongodb\"}",
     "legendFormat": "MongoDB"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_connections", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "MongoDB Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "MongoDB Operation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "MongoDB Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "mongodb_memory", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Collection Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "mongodb_collection_size_bytes", "legendFormat": "{{database}}-{{collection}}" }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total[1m])",
     "legendFormat": "Cache {{type}}"
    }
   ]
  }
 ]
}